# Generated by Django 2.1.5 on 2020-06-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bootcamp3',
            new_name='ProjectData',
        ),
    ]
