# Generated by Django 2.1.5 on 2020-06-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200616_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('Food_id', models.UUIDField(primary_key=True, serialize=False)),
                ('Food_Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField(max_length=20)),
                ('Quantity', models.IntegerField(max_length=20)),
                ('Item_Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Menu_id', models.UUIDField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField(max_length=20)),
                ('Food_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.UUIDField(primary_key=True, serialize=False)),
                ('Total_Quantity', models.IntegerField(max_length=20)),
                ('Total_Price', models.IntegerField(max_length=20)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Customer')),
                ('Food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('Time', models.IntegerField(max_length=20)),
                ('Date', models.IntegerField(max_length=20)),
                ('Payment_type', models.CharField(max_length=20)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Customer')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Order')),
            ],
        ),
    ]
